spring:
  application:
    name: seata-account-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        # 默认8719 假如被占用，会自动+1扫描，直到未被占用端口
        port: 8719
    alibaba:
      seata:
        # 自定义事务组名，需要与seata-servcer中的对应
        tx-service-group: fsp_tx_group
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
server:
  port: 2003

mybatis:
  mapperLocations: classpath:mapper/*.xml


feign:
  hystrix:
    enabled: false