spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8083

# 消费者去访问的微服务名
service-url:
  nacos-user-service: http://nacos-payment-provider